### ISSUE TITLE
Consider Alpine Linux as base image

### ISSUE THREAD

**Issue by douglascamata** [neckhair/rails-on-docker#4]
Alpine Linux is a very small distribution based on BusyBox and can help you build a very slim image. It's much more slimmer and lightweight than Ubuntu or even Debian images.

**Comment by neckhair** [comment]
Nice idea. It has some implications. For example I can't use the Brightbox Ruby packages anymore. But that's not a big one. I have no time currently but I'll look into this. Maybe you want to try it, @douglascamata, and create a PR?

**Comment by neckhair** [comment]
After installing all the dependencies for the Rails container the image has about 760MB. That's not much less then the Ubuntu image before. The Dockerfile could be more optimized, but this would decrease readability.
